export const GET_SELLER_INFO = 'GET_SELLER_INFO';
export const Add_GOODS_TO_CART = 'Add_GOODS_TO_CART';
export const DECREASE_GOODS_FROM_CART = 'DECREASE_GOODS_FROM_CART';
export const SHOPCART_SHOW_TAB = 'SHOPCART_SHOW_TAB';
